// ============================================================
// NOVA — dati: ingredienti, strumenti, ricette
// ============================================================

// --- Strumenti di cucina selezionabili ---
const APPLIANCES = [
  { id: "fornelli",   name: "Fornelli",            e: "🍳", d: "Piano cottura a gas o induzione" },
  { id: "forno",      name: "Forno",               e: "🔥", d: "Forno elettrico o a gas" },
  { id: "micro",      name: "Microonde",           e: "⚡", d: "Anche solo per scaldare" },
  { id: "airfryer",   name: "Friggitrice ad aria", e: "🍟", d: "Air fryer di qualsiasi misura" },
  { id: "frullatore", name: "Frullatore",          e: "🥤", d: "Frullatore o minipimer" },
  { id: "moka",       name: "Moka / caffettiera",  e: "☕", d: "Per il caffè vero" },
  { id: "bollitore",  name: "Bollitore",           e: "🫖", d: "Solo acqua bollente" },
];

// --- Categorie ingredienti (ordine di visualizzazione) ---
const CATEGORIES = [
  { id: "disp", name: "Pasta, riso e dispensa" },
  { id: "verd", name: "Verdure e aromi" },
  { id: "frut", name: "Frutta" },
  { id: "carn", name: "Carne e pesce" },
  { id: "latt", name: "Uova e latticini" },
  { id: "form", name: "Formaggi e salumi" },
  { id: "pane", name: "Pane e affini" },
  { id: "spez", name: "Spezie e condimenti" },
  { id: "dolc", name: "Dolci e colazione" },
];

// --- Ingredienti: id, nome, emoji, categoria ---
const INGREDIENTS = [
  // Dispensa
  { id: "spaghetti",  n: "Spaghetti",                     e: "🍝", c: "disp" },
  { id: "pastacorta", n: "Pasta corta (penne, fusilli…)", e: "🍝", c: "disp" },
  { id: "riso",       n: "Riso",                          e: "🍚", c: "disp" },
  { id: "gnocchi",    n: "Gnocchi di patate",             e: "🥟", c: "disp" },
  { id: "couscous",   n: "Couscous",                      e: "🥣", c: "disp" },
  { id: "noodles",    n: "Noodles istantanei",            e: "🍜", c: "disp" },
  { id: "farina",     n: "Farina 00",                     e: "🌾", c: "disp" },
  { id: "pangrattato",n: "Pangrattato",                   e: "🍞", c: "disp" },
  { id: "zucchero",   n: "Zucchero",                      e: "🥄", c: "disp" },
  { id: "lievito",    n: "Lievito per dolci",             e: "🥄", c: "disp" },
  { id: "passata",    n: "Passata di pomodoro",           e: "🍅", c: "disp" },
  { id: "tonno",      n: "Tonno sott'olio",               e: "🐟", c: "disp" },
  { id: "ceci",       n: "Ceci in scatola",               e: "🫘", c: "disp" },
  { id: "cannellini", n: "Fagioli cannellini",            e: "🫘", c: "disp" },
  { id: "lenticchie", n: "Lenticchie",                    e: "🫘", c: "disp" },
  { id: "mais",       n: "Mais in scatola",               e: "🌽", c: "disp" },
  { id: "olive",      n: "Olive",                         e: "🫒", c: "disp" },
  { id: "pesto",      n: "Pesto pronto",                  e: "🌿", c: "disp" },
  { id: "dado",       n: "Dado / brodo",                  e: "🍲", c: "disp" },
  { id: "cocco",      n: "Latte di cocco",                e: "🥥", c: "disp" },
  { id: "zafferano",  n: "Zafferano",                     e: "💛", c: "disp" },
  { id: "oliosemi",   n: "Olio di semi",                  e: "🫙", c: "disp" },
  // Verdure e aromi
  { id: "pomodorini", n: "Pomodorini",          e: "🍅", c: "verd" },
  { id: "pomodori",   n: "Pomodori",            e: "🍅", c: "verd" },
  { id: "cipolla",    n: "Cipolla",             e: "🧅", c: "verd" },
  { id: "aglio",      n: "Aglio",               e: "🧄", c: "verd" },
  { id: "zucchine",   n: "Zucchine",            e: "🥒", c: "verd" },
  { id: "melanzane",  n: "Melanzane",           e: "🍆", c: "verd" },
  { id: "peperoni",   n: "Peperoni",            e: "🫑", c: "verd" },
  { id: "patate",     n: "Patate",              e: "🥔", c: "verd" },
  { id: "carote",     n: "Carote",              e: "🥕", c: "verd" },
  { id: "funghi",     n: "Funghi champignon",   e: "🍄", c: "verd" },
  { id: "spinaci",    n: "Spinaci",             e: "🥬", c: "verd" },
  { id: "insalata",   n: "Insalata",            e: "🥬", c: "verd" },
  { id: "rucola",     n: "Rucola",              e: "🌿", c: "verd" },
  { id: "basilico",   n: "Basilico",            e: "🌿", c: "verd" },
  { id: "prezzemolo", n: "Prezzemolo",          e: "🌿", c: "verd" },
  { id: "rosmarino",  n: "Rosmarino",           e: "🌿", c: "verd" },
  // Frutta
  { id: "limone",   n: "Limone",           e: "🍋", c: "frut" },
  { id: "banana",   n: "Banane",           e: "🍌", c: "frut" },
  { id: "mele",     n: "Mele",             e: "🍎", c: "frut" },
  { id: "fragole",  n: "Fragole",          e: "🍓", c: "frut" },
  { id: "bosco",    n: "Frutti di bosco",  e: "🫐", c: "frut" },
  { id: "arancia",  n: "Arance",           e: "🍊", c: "frut" },
  // Carne e pesce
  { id: "pollo",     n: "Petto di pollo",            e: "🍗", c: "carn" },
  { id: "macinato",  n: "Carne macinata",            e: "🥩", c: "carn" },
  { id: "salsiccia", n: "Salsiccia",                 e: "🌭", c: "carn" },
  { id: "fettine",   n: "Fettine di vitello o pollo",e: "🥩", c: "carn" },
  { id: "salmone",   n: "Filetto di salmone",        e: "🐟", c: "carn" },
  // Uova e latticini
  { id: "uova",        n: "Uova",                 e: "🥚", c: "latt" },
  { id: "latte",       n: "Latte",                e: "🥛", c: "latt" },
  { id: "burro",       n: "Burro",                e: "🧈", c: "latt" },
  { id: "panna",       n: "Panna da cucina",      e: "🥛", c: "latt" },
  { id: "yogurt",      n: "Yogurt bianco",        e: "🥛", c: "latt" },
  { id: "yogurtgreco", n: "Yogurt greco",         e: "🥛", c: "latt" },
  { id: "mascarpone",  n: "Mascarpone",           e: "🧀", c: "latt" },
  { id: "mozzarella",  n: "Mozzarella",           e: "🧀", c: "latt" },
  { id: "spalmabile",  n: "Formaggio spalmabile", e: "🧀", c: "latt" },
  // Formaggi e salumi
  { id: "parmigiano", n: "Parmigiano",         e: "🧀", c: "form" },
  { id: "pecorino",   n: "Pecorino romano",    e: "🧀", c: "form" },
  { id: "guanciale",  n: "Guanciale",          e: "🥓", c: "form" },
  { id: "pancetta",   n: "Pancetta",           e: "🥓", c: "form" },
  { id: "cotto",      n: "Prosciutto cotto",   e: "🍖", c: "form" },
  { id: "crudo",      n: "Prosciutto crudo",   e: "🍖", c: "form" },
  { id: "sottilette", n: "Formaggio a fette",  e: "🧀", c: "form" },
  // Pane e affini
  { id: "pane",     n: "Pane",                 e: "🍞", c: "pane" },
  { id: "pancarre", n: "Pancarré",             e: "🍞", c: "pane" },
  { id: "piadine",  n: "Piadine",              e: "🫓", c: "pane" },
  { id: "buns",     n: "Panini da hamburger",  e: "🍔", c: "pane" },
  // Spezie e condimenti
  { id: "peperoncino", n: "Peperoncino",   e: "🌶️", c: "spez" },
  { id: "curry",       n: "Curry",         e: "🍛", c: "spez" },
  { id: "paprika",     n: "Paprika",       e: "🌶️", c: "spez" },
  { id: "cannella",    n: "Cannella",      e: "🟤", c: "spez" },
  { id: "origano",     n: "Origano",       e: "🌿", c: "spez" },
  { id: "soia",        n: "Salsa di soia", e: "🥢", c: "spez" },
  // Dolci e colazione
  { id: "nutella",    n: "Crema alle nocciole",  e: "🍫", c: "dolc" },
  { id: "marmellata", n: "Marmellata",           e: "🍓", c: "dolc" },
  { id: "miele",      n: "Miele",                e: "🍯", c: "dolc" },
  { id: "biscotti",   n: "Biscotti secchi",      e: "🍪", c: "dolc" },
  { id: "savoiardi",  n: "Savoiardi",            e: "🍪", c: "dolc" },
  { id: "cacao",      n: "Cacao amaro",          e: "🍫", c: "dolc" },
  { id: "fondente",   n: "Cioccolato fondente",  e: "🍫", c: "dolc" },
  { id: "gocce",      n: "Gocce di cioccolato",  e: "🍫", c: "dolc" },
  { id: "gelato",     n: "Gelato alla crema",    e: "🍨", c: "dolc" },
  { id: "caffe",      n: "Caffè macinato",       e: "☕", c: "dolc" },
  { id: "noci",       n: "Noci",                 e: "🌰", c: "dolc" },
];

// ============================================================
// RICETTE
//  - cat: primi | secondi | dolci
//  - app: strumenti richiesti; "a|b" = basta uno dei due; [] = nessuna cottura
//  - ing: [idIngrediente, quantità, opzionale?]
//         l'id può contenere "|" (alternative: basta averne uno)
//  Sale, pepe, olio extravergine e acqua sono dati per scontati.
// ============================================================
const RECIPES = [

  // ------------------------- PRIMI -------------------------
  {
    id: "aglio-olio", cat: "primi", name: "Spaghetti aglio, olio e peperoncino", e: "🍝",
    time: 15, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["spaghetti", "180 g"],
      ["aglio", "2 spicchi"],
      ["peperoncino", "1 (o una punta in polvere)"],
      ["prezzemolo", "un ciuffo", true],
    ],
    steps: [
      "Metti a bollire abbondante acqua salata e butta gli spaghetti.",
      "In una padella larga scalda 4 cucchiai d'olio a fuoco dolce con l'aglio a fettine e il peperoncino: deve dorare piano, senza mai bruciare.",
      "Scola la pasta 1 minuto prima del tempo indicato, tenendo da parte una tazza di acqua di cottura.",
      "Salta gli spaghetti in padella con un mestolino di acqua di cottura, mescolando finché si forma una cremina.",
      "Spegni, aggiungi il prezzemolo tritato se ce l'hai e servi subito.",
    ],
  },
  {
    id: "pomodoro", cat: "primi", name: "Pasta al pomodoro e basilico", e: "🍅",
    time: 20, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pastacorta", "180 g"],
      ["passata", "350 g"],
      ["aglio", "1 spicchio"],
      ["basilico", "qualche foglia"],
      ["parmigiano", "20 g", true],
    ],
    steps: [
      "Scalda 3 cucchiai d'olio con lo spicchio d'aglio schiacciato in un tegame.",
      "Versa la passata, sala, e lascia cuocere 10-15 minuti a fuoco medio-basso con qualche foglia di basilico.",
      "Intanto cuoci la pasta in acqua salata e scolala al dente.",
      "Manteca la pasta nel sugo per un minuto, togli l'aglio.",
      "Servi con basilico fresco e parmigiano.",
    ],
  },
  {
    id: "carbonara", cat: "primi", name: "Spaghetti alla carbonara", e: "🥓",
    time: 20, serves: "2 persone", diff: "Media", app: ["fornelli"],
    ing: [
      ["spaghetti", "180 g"],
      ["guanciale|pancetta", "80 g"],
      ["uova", "1 intero + 1 tuorlo"],
      ["pecorino", "50 g grattugiato"],
    ],
    steps: [
      "Taglia il guanciale a listarelle e rosolalo in padella senza olio, a fuoco medio, finché è croccante. Spegni e tieni il grasso.",
      "In una ciotola sbatti le uova con il pecorino e tanto pepe nero: deve venire una crema densa.",
      "Cuoci gli spaghetti in acqua salata e scolali al dente, tenendo una tazza d'acqua di cottura.",
      "FUORI DAL FUOCO, versa la pasta nella padella col guanciale, poi la crema di uova, mescolando forte.",
      "Aggiungi acqua di cottura poco alla volta finché la crema è lucida e avvolgente. Servi con altro pecorino e pepe.",
    ],
    note: "Il segreto: le uova non devono mai toccare il fuoco diretto, altrimenti diventa frittata.",
  },
  {
    id: "cacioepepe", cat: "primi", name: "Cacio e pepe", e: "🧀",
    time: 15, serves: "2 persone", diff: "Media", app: ["fornelli"],
    ing: [
      ["spaghetti", "180 g"],
      ["pecorino", "70 g grattugiato fine"],
    ],
    steps: [
      "Tosta una macinata abbondante di pepe nero in una padella larga, poi bagna con un mestolo d'acqua della pasta.",
      "Cuoci gli spaghetti in acqua poco salata (il pecorino è già sapido).",
      "In una ciotola mescola il pecorino con poca acqua di cottura tiepida fino ad avere una crema liscia.",
      "Scola la pasta molto al dente e finisci la cottura in padella con acqua di cottura.",
      "Spegni, aspetta 30 secondi, aggiungi la crema di pecorino e manteca velocemente.",
    ],
  },
  {
    id: "pasta-tonno", cat: "primi", name: "Pasta al tonno", e: "🐟",
    time: 15, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pastacorta", "180 g"],
      ["tonno", "160 g sgocciolato"],
      ["passata", "200 g"],
      ["aglio", "1 spicchio"],
      ["olive", "40 g", true],
    ],
    steps: [
      "Scalda 2 cucchiai d'olio con l'aglio, aggiungi la passata e cuoci 10 minuti.",
      "Unisci il tonno sgocciolato e le olive, mescola e spegni quasi subito per non stopparlo.",
      "Cuoci la pasta al dente e saltala nel sugo con un po' d'acqua di cottura.",
      "Una macinata di pepe e via, niente formaggio: col pesce non serve.",
    ],
  },
  {
    id: "burro-parmigiano", cat: "primi", name: "Pasta burro e parmigiano", e: "🧈",
    time: 12, serves: "2 persone", diff: "Facilissima", app: ["fornelli"],
    ing: [
      ["pastacorta", "180 g"],
      ["burro", "40 g"],
      ["parmigiano", "50 g grattugiato"],
    ],
    steps: [
      "Cuoci la pasta in acqua salata e scolala al dente, tenendo un po' d'acqua di cottura.",
      "Rimettila nella pentola con il burro a pezzetti e un mestolino d'acqua.",
      "Mescola energicamente aggiungendo il parmigiano in due volte, finché diventa cremosa.",
      "Pepe a piacere. Il piatto delle serate difficili.",
    ],
  },
  {
    id: "arrabbiata", cat: "primi", name: "Penne all'arrabbiata", e: "🌶️",
    time: 20, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pastacorta", "180 g"],
      ["passata", "300 g"],
      ["aglio", "2 spicchi"],
      ["peperoncino", "2 (o secondo coraggio)"],
      ["prezzemolo", "un ciuffo", true],
    ],
    steps: [
      "Scalda 3 cucchiai d'olio con aglio a fettine e peperoncino sbriciolato, a fuoco dolce.",
      "Aggiungi la passata, sala e cuoci 10-12 minuti.",
      "Cuoci le penne al dente e saltale nel sugo un minuto.",
      "Completa con prezzemolo tritato se ce l'hai.",
    ],
  },
  {
    id: "pasta-pesto", cat: "primi", name: "Pasta al pesto", e: "🌿",
    time: 12, serves: "2 persone", diff: "Facilissima", app: ["fornelli"],
    ing: [
      ["pastacorta", "180 g"],
      ["pesto", "80 g"],
      ["parmigiano", "20 g", true],
    ],
    steps: [
      "Cuoci la pasta in acqua salata e tieni da parte mezza tazza d'acqua di cottura.",
      "Metti il pesto in una ciotola grande e allungalo con un cucchiaio d'acqua di cottura: mai scaldarlo sul fuoco.",
      "Scola la pasta e mescolala nella ciotola col pesto.",
      "Spolvera di parmigiano e servi.",
    ],
  },
  {
    id: "sorrentina", cat: "primi", name: "Gnocchi alla sorrentina in padella", e: "🥟",
    time: 20, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["gnocchi", "500 g"],
      ["passata", "300 g"],
      ["mozzarella", "125 g"],
      ["basilico", "qualche foglia"],
      ["parmigiano", "30 g", true],
    ],
    steps: [
      "Prepara un sugo veloce: olio, passata, sale e basilico, 10 minuti in una padella larga.",
      "Cuoci gli gnocchi in acqua salata e scolali appena vengono a galla.",
      "Versali nel sugo, aggiungi la mozzarella a cubetti e il parmigiano.",
      "Mescola sul fuoco un minuto, finché la mozzarella fila. Coperchio, 2 minuti di riposo, e servi.",
    ],
  },
  {
    id: "risotto-zafferano", cat: "primi", name: "Risotto allo zafferano", e: "💛",
    time: 30, serves: "2 persone", diff: "Media", app: ["fornelli"],
    ing: [
      ["riso", "160 g"],
      ["zafferano", "1 bustina"],
      ["cipolla", "½"],
      ["burro", "40 g"],
      ["parmigiano", "40 g"],
      ["dado", "700 ml di brodo (1 dado)"],
    ],
    steps: [
      "Prepara il brodo con il dado e tienilo caldo a fianco.",
      "Soffriggi la cipolla tritata fine con metà del burro, poi tosta il riso 2 minuti mescolando.",
      "Aggiungi il brodo un mestolo alla volta, mescolando spesso, per 16-18 minuti.",
      "A metà cottura sciogli lo zafferano in un mestolo di brodo e versalo nel riso.",
      "Spegni, manteca con il burro restante e il parmigiano, coperchio 2 minuti. Deve essere \"all'onda\", non sodo.",
    ],
  },
  {
    id: "risotto-funghi", cat: "primi", name: "Risotto ai funghi", e: "🍄",
    time: 35, serves: "2 persone", diff: "Media", app: ["fornelli"],
    ing: [
      ["riso", "160 g"],
      ["funghi", "250 g"],
      ["cipolla", "½"],
      ["burro", "30 g"],
      ["parmigiano", "40 g"],
      ["dado", "700 ml di brodo (1 dado)"],
      ["prezzemolo", "un ciuffo", true],
    ],
    steps: [
      "Salta i funghi a fettine in padella con olio a fuoco vivo finché sono dorati. Sala e metti da parte.",
      "Soffriggi la cipolla tritata con un filo d'olio, tosta il riso 2 minuti.",
      "Porta a cottura aggiungendo brodo caldo un mestolo alla volta per 16-18 minuti.",
      "A 5 minuti dalla fine unisci i funghi.",
      "Spegni e manteca con burro e parmigiano. Prezzemolo tritato sopra e servi.",
    ],
  },
  {
    id: "pasta-ceci", cat: "primi", name: "Pasta e ceci", e: "🥣",
    time: 25, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pastacorta", "140 g"],
      ["ceci", "240 g sgocciolati (1 lattina)"],
      ["aglio", "1 spicchio"],
      ["rosmarino", "1 rametto"],
      ["passata", "100 g", true],
    ],
    steps: [
      "Soffriggi aglio e rosmarino in 3 cucchiai d'olio, aggiungi i ceci (e la passata se la usi) e insaporisci 5 minuti.",
      "Frulla o schiaccia metà dei ceci con la forchetta: renderà tutto più cremoso.",
      "Copri con 500 ml d'acqua calda, sala, e quando bolle butta la pasta direttamente dentro.",
      "Cuoci mescolando spesso: l'amido della pasta lega tutto. Aggiungi acqua se si asciuga troppo.",
      "Servi con un giro d'olio a crudo e pepe.",
    ],
  },
  {
    id: "couscous-tonno", cat: "primi", name: "Couscous freddo al tonno", e: "🥗",
    time: 15, serves: "2 persone", diff: "Facilissima", app: ["bollitore|fornelli|micro"],
    ing: [
      ["couscous", "120 g"],
      ["tonno", "160 g sgocciolato"],
      ["pomodorini", "150 g"],
      ["limone", "½"],
      ["olive", "40 g", true],
      ["mais", "80 g", true],
    ],
    steps: [
      "Porta a bollore 140 ml d'acqua (bollitore, pentolino o microonde).",
      "Versala sul couscous in una ciotola con un pizzico di sale e un filo d'olio, copri e aspetta 5 minuti.",
      "Sgrana il couscous con la forchetta.",
      "Aggiungi tonno, pomodorini a metà, olive e mais, condisci con olio, succo di limone, sale e pepe.",
      "Buono subito, meglio dopo mezz'ora in frigo.",
    ],
    note: "Zero fuochi: si fa anche in una stanza da studente col solo bollitore.",
  },
  {
    id: "noodles-up", cat: "primi", name: "Noodles istantanei, versione pro", e: "🍜",
    time: 10, serves: "1 persona", diff: "Facilissima", app: ["fornelli|bollitore|micro"],
    ing: [
      ["noodles", "1 confezione"],
      ["uova", "1"],
      ["soia", "1 cucchiaio", true],
      ["carote", "½ a julienne", true],
    ],
    steps: [
      "Prepara i noodles come da confezione, ma con un po' meno condimento in polvere.",
      "Mentre sono ancora bollenti, rompici dentro l'uovo e mescola subito: il calore lo cuoce in crema (o cuoci un uovo sodo/in camicia a parte e appoggialo sopra).",
      "Aggiungi la salsa di soia e le carote a julienne.",
      "Un filo d'olio piccante o peperoncino se ti piace.",
    ],
  },

  // ------------------------- SECONDI -------------------------
  {
    id: "pollo-limone", cat: "secondi", name: "Pollo al limone in padella", e: "🍗",
    time: 20, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pollo", "300 g"],
      ["limone", "1"],
      ["farina", "2 cucchiai", true],
      ["rosmarino", "1 rametto", true],
    ],
    steps: [
      "Taglia il petto di pollo a fettine non troppo spesse e, se vuoi, passale nella farina (verrà una salsina più legata).",
      "Scalda 3 cucchiai d'olio e rosola il pollo 3-4 minuti per lato a fuoco vivo.",
      "Sala, pepa, aggiungi il succo del limone e il rosmarino.",
      "Abbassa il fuoco e cuoci altri 2-3 minuti finché la salsa si addensa.",
    ],
  },
  {
    id: "pollo-curry", cat: "secondi", name: "Pollo al curry", e: "🍛",
    time: 25, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["pollo", "300 g"],
      ["curry", "1 cucchiaio"],
      ["cocco|panna", "200 ml"],
      ["cipolla", "½"],
      ["riso", "140 g", true],
    ],
    steps: [
      "Se lo vuoi col riso: cuocilo in acqua salata e tienilo da parte.",
      "Soffriggi la cipolla tritata in 2 cucchiai d'olio, aggiungi il pollo a bocconcini e rosolalo bene.",
      "Spolvera con il curry, mescola 1 minuto per tostarlo.",
      "Versa il latte di cocco (o la panna), sala e cuoci 10 minuti a fuoco basso finché la salsa si addensa.",
      "Servi con il riso bianco.",
    ],
  },
  {
    id: "frittata-zucchine", cat: "secondi", name: "Frittata di zucchine", e: "🍳",
    time: 15, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["uova", "4"],
      ["zucchine", "1 grande"],
      ["parmigiano", "30 g"],
      ["latte", "2 cucchiai", true],
    ],
    steps: [
      "Taglia la zucchina a rondelle sottili e falla saltare 5 minuti in padella con un filo d'olio e sale.",
      "Sbatti le uova con parmigiano, sale, pepe e il latte se lo usi.",
      "Versa le uova sulle zucchine, copri con un coperchio e cuoci a fuoco basso 6-7 minuti.",
      "Gira la frittata aiutandoti con un piatto (o passala 2 minuti sotto il grill) e finisci la cottura.",
    ],
  },
  {
    id: "uova-strapazzate", cat: "secondi", name: "Uova strapazzate cremose", e: "🥚",
    time: 8, serves: "1 persona", diff: "Facilissima", app: ["fornelli"],
    ing: [
      ["uova", "2-3"],
      ["burro", "15 g"],
      ["pane", "2 fette, tostate", true],
    ],
    steps: [
      "Sbatti le uova in una ciotola con un pizzico di sale.",
      "Sciogli il burro in un pentolino a fuoco BASSO, versa le uova.",
      "Mescola in continuazione con una spatola, togliendo dal fuoco ogni tanto: devono restare morbide e cremose, mai asciutte.",
      "Appena sono quasi pronte (2-3 minuti), spegni: finiscono di cuocersi da sole. Servi su pane tostato.",
    ],
  },
  {
    id: "uovo-micro", cat: "secondi", name: "Uovo in camicia al microonde", e: "⚡",
    time: 4, serves: "1 persona", diff: "Facilissima", app: ["micro"],
    ing: [
      ["uova", "1"],
      ["pane", "1 fetta, tostata", true],
    ],
    steps: [
      "Riempi una tazza con mezzo bicchiere d'acqua e un pizzico di sale.",
      "Rompici dentro l'uovo e buca il tuorlo con uno stuzzicadenti (importante: altrimenti può scoppiare).",
      "Copri con un piattino e cuoci 50-60 secondi a 750W. Se l'albume non è rappreso, altri 10-15 secondi.",
      "Scolalo con un cucchiaio e servilo su pane tostato con pepe e un filo d'olio.",
    ],
  },
  {
    id: "pollo-airfryer", cat: "secondi", name: "Straccetti di pollo croccanti in air fryer", e: "🍗",
    time: 25, serves: "2 persone", diff: "Facile", app: ["airfryer"],
    ing: [
      ["pollo", "400 g"],
      ["uova", "1"],
      ["pangrattato", "80 g"],
      ["parmigiano", "30 g"],
      ["paprika", "1 cucchiaino", true],
    ],
    steps: [
      "Taglia il pollo a straccetti, salali e passali prima nell'uovo sbattuto.",
      "Poi nel pangrattato mescolato con parmigiano e paprika, premendo bene.",
      "Disponili nel cestello senza sovrapporli, un filo d'olio spruzzato sopra.",
      "Cuoci a 200 °C per 12-14 minuti, girandoli a metà. Devono essere dorati e croccanti.",
    ],
  },
  {
    id: "salmone", cat: "secondi", name: "Salmone al limone", e: "🐟",
    time: 18, serves: "2 persone", diff: "Facile", app: ["airfryer|forno"],
    ing: [
      ["salmone", "2 filetti"],
      ["limone", "1"],
      ["aglio", "1 spicchio", true],
      ["prezzemolo", "un ciuffo", true],
    ],
    steps: [
      "Condisci i filetti con olio, sale, pepe, succo di mezzo limone e aglio a fettine se ti piace.",
      "In air fryer: 180 °C per 8-10 minuti. In forno: 200 °C per 12-15 minuti.",
      "Il salmone è pronto quando si sfalda facilmente con la forchetta ma è ancora rosato dentro.",
      "Finisci con prezzemolo e l'altro mezzo limone a spicchi.",
    ],
  },
  {
    id: "patate-airfryer", cat: "secondi", name: "Patate croccanti (contorno)", e: "🍟",
    time: 30, serves: "2 persone", diff: "Facile", app: ["airfryer|forno"],
    ing: [
      ["patate", "500 g"],
      ["paprika", "1 cucchiaino", true],
      ["rosmarino", "1 rametto", true],
    ],
    steps: [
      "Taglia le patate a spicchi o bastoncini e sciacquale in acqua fredda per togliere l'amido. Asciugale BENE.",
      "Condiscile con un cucchiaio d'olio, sale, paprika e rosmarino.",
      "In air fryer: 190 °C per 18-20 minuti scuotendo il cestello a metà. In forno: 200 °C per 30-35 minuti.",
      "Croccanti fuori, morbide dentro. Sala ancora un po' appena uscite.",
    ],
  },
  {
    id: "hamburger", cat: "secondi", name: "Hamburger fatto in casa", e: "🍔",
    time: 20, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["macinato", "300 g"],
      ["buns", "2"],
      ["insalata", "qualche foglia"],
      ["pomodori", "1"],
      ["sottilette", "2", true],
      ["cipolla", "½ ad anelli", true],
    ],
    steps: [
      "Forma 2 burger con il macinato, sale e pepe: schiacciali bene, poco più larghi del panino (in cottura si ritirano).",
      "Scalda forte una padella e cuocili 3-4 minuti per lato senza schiacciarli mai con la spatola.",
      "Nell'ultimo minuto appoggia il formaggio sul burger e copri per farlo sciogliere.",
      "Tosta i panini nella stessa padella e componi: insalata, burger, pomodoro, cipolla.",
    ],
  },
  {
    id: "polpette", cat: "secondi", name: "Polpette al sugo", e: "🍝",
    time: 40, serves: "3 persone", diff: "Media", app: ["fornelli"],
    ing: [
      ["macinato", "400 g"],
      ["uova", "1"],
      ["pangrattato", "60 g"],
      ["parmigiano", "40 g"],
      ["passata", "400 g"],
      ["aglio", "1 spicchio"],
      ["prezzemolo", "un ciuffo", true],
    ],
    steps: [
      "Impasta macinato, uovo, pangrattato, parmigiano, sale, pepe e prezzemolo. Forma polpette da noce grande.",
      "Rosolale in padella con 3 cucchiai d'olio finché sono dorate fuori (dentro possono essere crude).",
      "Toglile, e nella stessa padella fai il sugo: aglio, passata, sale, 5 minuti.",
      "Rimetti le polpette nel sugo, coperchio, e cuoci 15-20 minuti a fuoco basso.",
      "Da fare scarpetta obbligatoria.",
    ],
  },
  {
    id: "scaloppine", cat: "secondi", name: "Scaloppine al limone", e: "🍋",
    time: 15, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["fettine", "300 g"],
      ["farina", "30 g"],
      ["burro", "40 g"],
      ["limone", "1"],
    ],
    steps: [
      "Infarina le fettine da entrambi i lati, scuotendo via l'eccesso.",
      "Sciogli il burro in padella e cuoci le fettine 2 minuti per lato a fuoco medio-alto.",
      "Sala, aggiungi il succo di limone e mezzo bicchiere d'acqua.",
      "Cuoci 2-3 minuti finché la salsa diventa lucida e leggermente densa.",
    ],
  },
  {
    id: "salsiccia-patate", cat: "secondi", name: "Salsiccia e patate al forno", e: "🌭",
    time: 45, serves: "2 persone", diff: "Facile", app: ["forno|airfryer"],
    ing: [
      ["salsiccia", "4"],
      ["patate", "600 g"],
      ["rosmarino", "2 rametti"],
    ],
    steps: [
      "Taglia le patate a spicchi, condiscile con olio, sale e rosmarino.",
      "Bucherella le salsicce con una forchetta e mettile in teglia con le patate.",
      "In forno: 200 °C per 40 minuti, girando a metà. In air fryer: 190 °C per 25 minuti circa.",
      "Il grasso della salsiccia insaporisce le patate: è il punto di tutta la ricetta.",
    ],
  },
  {
    id: "verdure-forno", cat: "secondi", name: "Verdure al forno", e: "🥗",
    time: 35, serves: "2 persone", diff: "Facilissima", app: ["forno|airfryer"],
    ing: [
      ["zucchine", "1"],
      ["melanzane", "1"],
      ["peperoni", "1"],
      ["patate", "2", true],
      ["origano", "una spolverata"],
    ],
    steps: [
      "Taglia tutte le verdure a pezzi della stessa dimensione (cuociono uniformi).",
      "Condiscile con olio, sale, pepe e origano direttamente sulla teglia.",
      "In forno: 200 °C per 30-35 minuti mescolando una volta. In air fryer: 180 °C per 18-20 minuti.",
      "Ottime calde, ottime fredde il giorno dopo, ottime dentro una piadina.",
    ],
  },
  {
    id: "parmigiana", cat: "secondi", name: "Parmigiana di melanzane veloce", e: "🍆",
    time: 50, serves: "3 persone", diff: "Media", app: ["fornelli", "forno|airfryer"],
    ing: [
      ["melanzane", "2"],
      ["passata", "400 g"],
      ["mozzarella", "250 g"],
      ["parmigiano", "60 g"],
      ["basilico", "qualche foglia"],
    ],
    steps: [
      "Taglia le melanzane a fette da mezzo cm e grigliale in padella ben calda con poco olio (versione leggera, niente frittura).",
      "Prepara un sugo veloce: olio, passata, sale, basilico, 10 minuti.",
      "In una pirofila alterna: sugo, melanzane, mozzarella a pezzi, parmigiano. Ripeti per 3 strati, finendo con sugo e parmigiano.",
      "In forno a 200 °C per 25 minuti (o in air fryer a 180 °C per 15) finché gratina.",
      "Aspetta 10 minuti prima di tagliarla: si compatta e si serve meglio.",
    ],
  },
  {
    id: "caprese", cat: "secondi", name: "Caprese", e: "🍅",
    time: 5, serves: "2 persone", diff: "Facilissima", app: [],
    ing: [
      ["mozzarella", "250 g"],
      ["pomodori", "2 maturi"],
      ["basilico", "qualche foglia"],
      ["origano", "una spolverata", true],
    ],
    steps: [
      "Taglia pomodori e mozzarella a fette dello stesso spessore.",
      "Alternali su un piatto, una fetta e una foglia di basilico.",
      "Condisci con olio buono, sale e origano solo all'ultimo momento (il sale fa spurgare i pomodori).",
    ],
  },
  {
    id: "tonno-cannellini", cat: "secondi", name: "Insalata di tonno e cannellini", e: "🥫",
    time: 10, serves: "2 persone", diff: "Facilissima", app: [],
    ing: [
      ["tonno", "160 g sgocciolato"],
      ["cannellini", "240 g sgocciolati (1 lattina)"],
      ["cipolla", "½ (rossa se ce l'hai)"],
      ["limone", "½", true],
    ],
    steps: [
      "Sciacqua i cannellini sotto l'acqua fredda e scolali bene.",
      "Affetta la cipolla sottilissima (10 minuti in acqua fredda la rende più dolce).",
      "Mescola tutto con il tonno, condisci con olio, sale, pepe e succo di limone.",
      "Pronto in 10 minuti, proteico, zero cottura.",
    ],
  },
  {
    id: "toast", cat: "secondi", name: "Toast prosciutto e formaggio", e: "🥪",
    time: 8, serves: "1 persona", diff: "Facilissima", app: ["fornelli|airfryer"],
    ing: [
      ["pancarre", "4 fette"],
      ["cotto", "2 fette"],
      ["sottilette", "2"],
    ],
    steps: [
      "Componi i toast: pane, formaggio, prosciutto, formaggio, pane (il doppio formaggio incolla tutto).",
      "In padella: fuoco medio-basso con una noce di burro, 2-3 minuti per lato schiacciando con una spatola.",
      "In air fryer: 180 °C per 5-6 minuti.",
      "Pronto quando è dorato fuori e il formaggio fila.",
    ],
  },
  {
    id: "piadina", cat: "secondi", name: "Piadina crudo, formaggio e rucola", e: "🫓",
    time: 8, serves: "1 persona", diff: "Facilissima", app: ["fornelli"],
    ing: [
      ["piadine", "1"],
      ["crudo", "80 g"],
      ["spalmabile|mozzarella", "80 g"],
      ["rucola", "una manciata"],
    ],
    steps: [
      "Scalda la piadina in padella 1 minuto per lato, senza condimenti.",
      "Spalma il formaggio (o distribuisci la mozzarella a fette sottili).",
      "Aggiungi crudo e rucola, piega a metà.",
      "Altri 30 secondi in padella se la vuoi calda e filante.",
    ],
  },

  {
    id: "zuppa-lenticchie", cat: "secondi", name: "Zuppa di lenticchie", e: "🥣",
    time: 35, serves: "2 persone", diff: "Facile", app: ["fornelli"],
    ing: [
      ["lenticchie", "250 g (in scatola: 1 lattina)"],
      ["carote", "1"],
      ["cipolla", "½"],
      ["passata", "150 g", true],
      ["rosmarino", "1 rametto", true],
      ["pane", "2 fette, tostate", true],
    ],
    steps: [
      "Soffriggi cipolla e carota a dadini in 3 cucchiai d'olio per 5 minuti.",
      "Aggiungi le lenticchie (se secche, prima sciacquale; in scatola, scolale), la passata e il rosmarino.",
      "Copri d'acqua calda e cuoci: 25-30 minuti se secche, 10 minuti se in scatola. Sala alla fine.",
      "Servi con un giro d'olio a crudo, pepe e pane tostato.",
    ],
  },
  {
    id: "spinaci-saltati", cat: "secondi", name: "Spinaci saltati con parmigiano (contorno)", e: "🥬",
    time: 12, serves: "2 persone", diff: "Facilissima", app: ["fornelli"],
    ing: [
      ["spinaci", "400 g freschi (o 300 g surgelati)"],
      ["aglio", "1 spicchio"],
      ["parmigiano", "20 g", true],
      ["limone", "una spruzzata", true],
    ],
    steps: [
      "Scalda 2 cucchiai d'olio con l'aglio schiacciato in una padella larga.",
      "Aggiungi gli spinaci (freschi: appena lavati, ancora bagnati) e copri 2 minuti: crollano subito.",
      "Scoperchia, sala e salta a fuoco vivo finché l'acqua è evaporata.",
      "Fuori dal fuoco: scaglie di parmigiano e una spruzzata di limone.",
    ],
  },

  // ------------------------- DOLCI -------------------------
  {
    id: "mugcake", cat: "dolci", name: "Mug cake al cioccolato", e: "☕",
    time: 5, serves: "1 persona", diff: "Facilissima", app: ["micro"],
    ing: [
      ["farina", "4 cucchiai"],
      ["cacao", "2 cucchiai"],
      ["zucchero", "3 cucchiai"],
      ["latte", "60 ml"],
      ["oliosemi", "2 cucchiai"],
      ["lievito", "½ cucchiaino"],
      ["gocce", "1 cucchiaio", true],
    ],
    steps: [
      "In una tazza grande mescola farina, cacao, zucchero e lievito.",
      "Aggiungi latte e olio, mescola bene fino a impasto liscio. Gocce di cioccolato sopra se le hai.",
      "Microonde a 800W per 90 secondi. Se è ancora liquida al centro, altri 15-20 secondi.",
      "Aspetta un minuto (scotta!) e mangiala direttamente dalla tazza.",
    ],
    note: "La torta al cioccolato più veloce del mondo: 5 minuti da voglia a cucchiaino.",
  },
  {
    id: "tiramisu", cat: "dolci", name: "Tiramisù classico", e: "☕",
    time: 30, serves: "6 persone", diff: "Media", app: ["moka"],
    ing: [
      ["savoiardi", "300 g"],
      ["mascarpone", "500 g"],
      ["uova", "4 freschissime"],
      ["zucchero", "100 g"],
      ["caffe", "4 tazzine di moka"],
      ["cacao", "per spolverare"],
    ],
    steps: [
      "Prepara il caffè con la moka, zuccheralo poco e lascialo raffreddare in un piatto fondo.",
      "Separa tuorli e albumi. Monta i tuorli con lo zucchero finché sono chiari e spumosi, poi incorpora il mascarpone.",
      "Monta gli albumi a neve ferma e incorporali delicatamente dal basso verso l'alto.",
      "Inzuppa velocemente i savoiardi nel caffè (bagnati fuori, asciutti dentro) e fai uno strato in una pirofila.",
      "Copri con crema, ripeti gli strati e finisci con la crema. Frigo almeno 4 ore, cacao spolverato solo prima di servire.",
    ],
    note: "Le uova restano crude: usale freschissime e tieni il tiramisù sempre in frigo.",
  },
  {
    id: "affogato", cat: "dolci", name: "Affogato al caffè", e: "🍨",
    time: 5, serves: "1 persona", diff: "Facilissima", app: ["moka"],
    ing: [
      ["gelato", "2 palline"],
      ["caffe", "1 tazzina di moka"],
      ["fondente", "qualche scaglia", true],
    ],
    steps: [
      "Metti due palline di gelato in una coppa fredda di freezer.",
      "Prepara un caffè bollente con la moka.",
      "Versalo direttamente sul gelato e completa con scaglie di fondente.",
      "Mangialo subito: il bello è il contrasto caldo-freddo.",
    ],
  },
  {
    id: "torta-cioccolato", cat: "dolci", name: "Torta al cioccolato morbida", e: "🍫",
    time: 50, serves: "8 persone", diff: "Media", app: ["forno"],
    ing: [
      ["farina", "200 g"],
      ["zucchero", "180 g"],
      ["cacao", "60 g"],
      ["uova", "3"],
      ["burro", "100 g fuso"],
      ["latte", "100 ml"],
      ["lievito", "1 bustina"],
    ],
    steps: [
      "Accendi il forno a 180 °C. Monta le uova con lo zucchero 3-4 minuti: devono gonfiare.",
      "Aggiungi il burro fuso tiepido e il latte, mescolando.",
      "Setaccia farina, cacao e lievito e incorporali poco alla volta.",
      "Versa in una tortiera imburrata (22-24 cm) e cuoci 35-40 minuti.",
      "Prova stecchino: deve uscire quasi asciutto. Il \"quasi\" è quello che la tiene umida.",
    ],
  },
  {
    id: "ciambellone", cat: "dolci", name: "Ciambellone allo yogurt", e: "🍩",
    time: 55, serves: "8 persone", diff: "Facile", app: ["forno"],
    ing: [
      ["yogurt", "250 g"],
      ["uova", "3"],
      ["zucchero", "180 g"],
      ["farina", "300 g"],
      ["oliosemi", "100 ml"],
      ["lievito", "1 bustina"],
      ["limone", "scorza grattugiata", true],
    ],
    steps: [
      "Forno a 180 °C. Sbatti uova e zucchero, poi aggiungi yogurt, olio e la scorza di limone.",
      "Incorpora farina e lievito setacciati, mescolando fino a impasto liscio.",
      "Versa nello stampo a ciambella imburrato e infarinato.",
      "Cuoci 40-45 minuti senza MAI aprire il forno nella prima mezz'ora.",
      "Il dolce da colazione che dura tutta la settimana (in teoria).",
    ],
  },
  {
    id: "cookies", cat: "dolci", name: "Cookies alle gocce di cioccolato", e: "🍪",
    time: 25, serves: "15 biscotti", diff: "Facile", app: ["forno|airfryer"],
    ing: [
      ["burro", "100 g morbido"],
      ["zucchero", "100 g"],
      ["uova", "1"],
      ["farina", "200 g"],
      ["gocce", "120 g"],
      ["lievito", "½ cucchiaino"],
    ],
    steps: [
      "Lavora il burro morbido con lo zucchero, poi aggiungi l'uovo e un pizzico di sale.",
      "Incorpora farina e lievito, infine le gocce di cioccolato.",
      "Forma palline da noce e schiacciale appena sulla teglia con carta forno, ben distanziate.",
      "In forno: 180 °C per 12-14 minuti. In air fryer: 160 °C per 8-9 minuti, in più tornate.",
      "Sembrano crudi al centro quando escono: è giusto così, induriscono raffreddandosi.",
    ],
  },
  {
    id: "pancakes", cat: "dolci", name: "Pancakes", e: "🥞",
    time: 20, serves: "2 persone (8 pancakes)", diff: "Facile", app: ["fornelli"],
    ing: [
      ["farina", "200 g"],
      ["latte", "200 ml"],
      ["uova", "2"],
      ["zucchero", "2 cucchiai"],
      ["lievito", "1 cucchiaino"],
      ["burro", "20 g fuso"],
      ["miele|nutella|marmellata", "per servire", true],
    ],
    steps: [
      "Mescola gli ingredienti secchi (farina, zucchero, lievito, pizzico di sale).",
      "A parte sbatti uova, latte e burro fuso, poi unisci ai secchi: mescola poco, i grumi piccoli vanno bene.",
      "Scalda una padella antiaderente a fuoco medio con pochissimo burro.",
      "Versa mezzo mestolo per pancake: gira quando la superficie fa le bollicine (1-2 minuti per lato).",
      "Impilali e condiscili con miele, nutella o marmellata.",
    ],
  },
  {
    id: "crepes", cat: "dolci", name: "Crêpes dolci", e: "🥞",
    time: 25, serves: "2 persone (6 crêpes)", diff: "Facile", app: ["fornelli"],
    ing: [
      ["farina", "125 g"],
      ["latte", "250 ml"],
      ["uova", "2"],
      ["burro", "20 g fuso"],
      ["nutella|marmellata", "per farcire"],
    ],
    steps: [
      "Frulla o sbatti farina, latte, uova, burro fuso e un pizzico di sale: pastella liscia e fluida.",
      "Lasciala riposare 15 minuti se hai pazienza (vengono più elastiche).",
      "Scalda una padella antiaderente, ungila appena e versa un mestolo scarso ruotando la padella per coprire il fondo.",
      "Un minuto per lato: gira quando i bordi si staccano da soli.",
      "Farcisci con nutella o marmellata e piega a triangolo.",
    ],
  },
  {
    id: "salame-cioccolato", cat: "dolci", name: "Salame di cioccolato", e: "🍫",
    time: 20, serves: "6 persone", diff: "Facile", app: [],
    ing: [
      ["biscotti", "200 g"],
      ["burro", "100 g morbido"],
      ["zucchero", "80 g"],
      ["cacao", "50 g"],
      ["latte", "3 cucchiai"],
    ],
    steps: [
      "Spezza i biscotti a mano in pezzi grossolani (non polvere: i pezzi fanno l'effetto \"salame\").",
      "Lavora burro morbido, zucchero e cacao fino a crema, ammorbidendo col latte.",
      "Unisci i biscotti e mescola bene.",
      "Forma un salame sulla carta forno, arrotola stretto e chiudi le estremità a caramella.",
      "Frigo almeno 3 ore, poi taglia a fette. Senza uova crude, senza cottura.",
    ],
  },
  {
    id: "macedonia", cat: "dolci", name: "Macedonia al limone e miele", e: "🍓",
    time: 10, serves: "2 persone", diff: "Facilissima", app: [],
    ing: [
      ["mele", "1"],
      ["banana", "1"],
      ["arancia", "1"],
      ["fragole", "150 g"],
      ["limone", "½"],
      ["miele|zucchero", "1 cucchiaio", true],
    ],
    steps: [
      "Taglia tutta la frutta a pezzi in una ciotola.",
      "Condisci con il succo di limone (evita anche che la frutta annerisca) e il miele.",
      "Mescola e lascia riposare 15 minuti in frigo: i succhi si mischiano e fanno lo \"sciroppo\".",
    ],
  },
  {
    id: "smoothie", cat: "dolci", name: "Smoothie di frutta", e: "🥤",
    time: 5, serves: "1 persona", diff: "Facilissima", app: ["frullatore"],
    ing: [
      ["banana", "1"],
      ["fragole|bosco", "150 g"],
      ["latte|yogurt", "150 ml"],
      ["miele", "1 cucchiaino", true],
    ],
    steps: [
      "Metti nel frullatore la banana a pezzi, i frutti e il latte (o lo yogurt).",
      "Frulla 30-40 secondi fino a consistenza liscia.",
      "Assaggia: se la frutta è matura non serve nemmeno il miele.",
      "Con la banana congelata a pezzi viene ancora più cremoso, quasi gelato.",
    ],
  },
  {
    id: "coppa-greco", cat: "dolci", name: "Coppa di yogurt greco, miele e noci", e: "🍯",
    time: 5, serves: "2 persone", diff: "Facilissima", app: [],
    ing: [
      ["yogurtgreco", "300 g"],
      ["miele", "2 cucchiai"],
      ["noci", "40 g"],
      ["bosco", "una manciata", true],
    ],
    steps: [
      "Dividi lo yogurt greco in due coppette.",
      "Spezzetta le noci con le mani e distribuiscile sopra.",
      "Un giro generoso di miele e i frutti di bosco se li hai.",
      "Colazione, merenda o dolce dopo cena: funziona sempre.",
    ],
  },
  {
    id: "mele-micro", cat: "dolci", name: "Mele «al forno» al microonde", e: "🍎",
    time: 8, serves: "2 persone", diff: "Facilissima", app: ["micro"],
    ing: [
      ["mele", "2"],
      ["zucchero", "2 cucchiai"],
      ["cannella", "una spolverata"],
      ["biscotti", "2, sbriciolati", true],
    ],
    steps: [
      "Sbuccia le mele, tagliale a spicchi e mettile in una ciotola adatta al microonde.",
      "Cospargile con zucchero, cannella e un cucchiaio d'acqua.",
      "Copri con un piatto e cuoci 4-5 minuti a 800W, finché sono morbide.",
      "Completa con i biscotti sbriciolati sopra: effetto crumble in 8 minuti.",
    ],
  },
  {
    id: "banana-bread", cat: "dolci", name: "Banana bread", e: "🍌",
    time: 60, serves: "8 persone", diff: "Facile", app: ["forno"],
    ing: [
      ["banana", "3 molto mature"],
      ["farina", "250 g"],
      ["zucchero", "100 g"],
      ["uova", "2"],
      ["burro", "80 g fuso"],
      ["lievito", "1 bustina"],
      ["cannella", "1 cucchiaino", true],
      ["noci|gocce", "80 g", true],
    ],
    steps: [
      "Forno a 180 °C. Schiaccia le banane con la forchetta fino a purea (più sono mature e nere, meglio è).",
      "Aggiungi uova, zucchero e burro fuso, mescolando.",
      "Incorpora farina, lievito e cannella, poi noci o gocce di cioccolato.",
      "Versa in uno stampo da plumcake e cuoci 50-55 minuti (prova stecchino).",
      "Il modo migliore per salvare le banane troppo mature.",
    ],
  },
  {
    id: "crumble", cat: "dolci", name: "Crumble di mele", e: "🥧",
    time: 45, serves: "4 persone", diff: "Facile", app: ["forno"],
    ing: [
      ["mele", "4"],
      ["farina", "150 g"],
      ["burro", "100 g freddo"],
      ["zucchero", "120 g"],
      ["cannella", "1 cucchiaino"],
    ],
    steps: [
      "Forno a 180 °C. Taglia le mele a cubetti e mettile in una pirofila con 40 g di zucchero e la cannella.",
      "Con la punta delle dita sbriciola burro freddo, farina e lo zucchero restante fino ad avere briciole grosse.",
      "Copri le mele con le briciole senza compattarle.",
      "Cuoci 35 minuti finché la superficie è dorata e sotto sobbolle.",
      "Da servire tiepido, con gelato alla crema se ce l'hai.",
    ],
  },
];
